product_name= input("item name-")
quantity= int(input("product quantity-"))
price= int(input("enter price-"))
print ("item name  :",product_name)
print ("quantity   :",quantity)
print ("price      :",price)